### ISSUE TITLE
Customizer hidding modules functionality 

### ISSUE THREAD

**Issue by bpaniagua** [pieper/CustomSlicerGenerator#7]
Thank you so much, @juanprietob. This functionality works in Mac OS but does not seem to work in Windows.

**Comment by bpaniagua** [comment]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\paniagub.AD\Desktop\SlicerCMF3-0\Package\SlicerCMF3-0\bin\Python\slicer\util.py", line 158, in findChildren
    if hasattr(p, attribute) and fnmatch.fnmatchcase(getattr(p, attribute), kwargs[attribute]):
  File "C:\Users\paniagub.AD\Desktop\SlicerCMF3-0\Package\SlicerCMF3-0\lib\Python\Lib\fnmatch.py", line 83, in fnmatchcase
    return re_pat.match(name) is not None
TypeError: expected string or buffer

**Comment by juanprietob** [comment]
The line 

`mm = slicer.util.findChildren(className='qSlicerModulesMenu')[0]` in file https://github.com/pieper/CustomSlicerGenerator/blob/00423c082eae1329c6e9c93d7e53f3aa199e7d32/Customizer/Customizer.py#L70

This instruction outputs the following error in windows only:
`slicer.util.findChildren(className='qSlicerModulesMenu')`

`Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\paniagub.AD\Desktop\SlicerCMF3-0\Package\SlicerCMF3-0\bin\Python\slicer\util.py", line 158, in findChildren
if hasattr(p, attribute) and fnmatch.fnmatchcase(getattr(p, attribute), kwargs[attribute]):
File "C:\Users\paniagub.AD\Desktop\SlicerCMF3-0\Package\SlicerCMF3-0\lib\Python\Lib\fnmatch.py", line 83, in fnmatchcase
return re_pat.match(name) is not None
TypeError: expected string or buffer`

**Comment by juanprietob** [comment]
Update:
it seems this instruction does not work for the nightly version of Slicer

**Comment by pieper** [comment]
Hi @bpaniagua, @juanprietob - is this still an unresolved issue?  I'd be happy to look at it and clean up this loose end.

Thanks,

**Comment by juanprietob** [comment]
This issue was solved later on.

**Comment by pieper** [comment]
Great - I'll close it then!
